name: Build
on:
  push:
    branches:
      - *

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH

      - name: Get Pkger
        run: |
          go get github.com/markbates/pkger/cmd/pkger
          pkger

      - name: Set Develop App Version
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "APP_VERSION=$(go run . --version)-alpha.${{ github.run_number }}" >> $GITHUB_ENV
          echo "FORMULA_SUFFIX=-dev" >> $GITHUB_ENV

      - name: Set Main App Version
        if: github.ref == 'refs/heads/main'
        run: |
          echo "APP_VERSION=$(echo $(go run . --version))" >> $GITHUB_ENV
          echo "FORMULA_SUFFIX=" >> $GITHUB_ENV

      - name: Build
        run: |
          go mod download
          go mod verify
          go build -o ./all